config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users
  # Defines the root path route ("/")
  resources :users
  resource :shopping_cart, only: %i[show]
  resources :devil_fruits do
    resources :cart_items, only: %i[create]
  end
  resources :cart_items, only: %i[show update destroy]

  get "search", to: "devil_fruits#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :devil_fruit, optional: true
  belongs_to :shopping_cart, optional: true
end

app/models/devil_fruit.rb
class DevilFruit < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :shopping_carts, optional: true
  has_many :cart_items, dependent: :destroy
  has_one_attached :photo
  # validates :name, presence: true
  # validates :price, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :devil_fruits, through: :cart_items
  has_many :cart_items
  # validates :is_full?, presence: true
  def is_full?
    shopping_cart.devil_fruits.count != 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :shopping_cart, dependent: :destroy
  has_many :devil_fruits
  has_many :cart_items, through: :shopping_cart
  #   validates :email, presence: true, confirmation: true
  #   validates :encrypted_password, presence: true, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: %i[show destroy]
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def show
  end

  def new
    @cart_item = CartItem.new
  end

  def create
    @chosen_devil_fruit = DevilFruit.find(params[:devil_fruit_id])
    @shopping_cart = current_user.shopping_cart || current_user.create_shopping_cart
    @cart_item = @shopping_cart.cart_items.build(devil_fruit: @chosen_devil_fruit)

    if @cart_item.save
      redirect_to shopping_cart_path
    else
      render :new
    end
  end

  # def update (WE DONT NEED IT FOR NOW!)
  #   if @cart_item.update(cart_item_params)
  #     redirect_to @cart_item.shopping_cart
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to shopping_cart_path(@shopping_cart)
  end

  private

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:devil_fruit_id, :shopping_cart_id)
  end
end

app/controllers/devil_fruits_controller.rb
class DevilFruitsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    if params[:query].present?
      @devil_fruits = policy_scope(DevilFruit.where("name ILIKE ?", "%#{params[:query]}%"))
    else
      @devil_fruits = policy_scope(DevilFruit.all)
    end
  end

  def show
    @devil_fruit = DevilFruit.find(params[:id])
    authorize @devil_fruit
    # @chosen_devil_fruit
  end

  def new
    @devil_fruit = DevilFruit.new
    authorize @devil_fruit
  end

  def create
    @devil_fruit = DevilFruit.new(devil_fruit_params)
    @devil_fruit.user = current_user
    authorize @devil_fruit
    if @devil_fruit.save
      redirect_to @devil_fruit
    else
      render :new
    end
  end

  def edit
    @devil_fruit = DevilFruit.find(params[:id])
    authorize @devil_fruit
  end

  def update
    @devil_fruit = DevilFruit.find(params[:id])
    authorize @devil_fruit
    if @devil_fruit.update(devil_fruit_params)
      redirect_to @devil_fruit
    else
      render :edit
    end
  end

  def destroy
    @devil_fruit = DevilFruit.find(params[:id])
    authorize @devil_fruit
    @devil_fruit.destroy
    redirect_to devil_fruits_url, notice: "Devil fruit has been destroyed!"
  end

  private

  def devil_fruit_params
    params.require(:devil_fruit).permit(:name, :description, :price, :status, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @devil_fruits = DevilFruit.all
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: %i[show edit]
  before_action :authenticate_user!
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def show
    @cart_items = current_user.cart_items
    puts "@cart_items = #{@cart_items.inspect}"
  end

  def edit
  end

  def update
    if @shopping_cart.update(shopping_cart_params)
      redirect_to shopping_cart_path(@shopping_cart)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  private

  def shopping_cart_params
    params.require(:shopping_cart).permit(:is_full?)
  end

  def set_shopping_cart
    @shopping_cart = current_user.shopping_cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/new.html.erb
<%# <h1>add cart_item</h1> %>
<%# <%= simple_form_for(@cart_item) do |f| %>
  <%# <%= f.input :devil_fruits_id %>
  <%# <%= f.input :shopping_cart_id %>
  <%# <%= f.submit %>
<%# <% end %>

app/views/cart_items/show.html.erb
<div class="container">
  <h1 class="font-alpha">Your choosen Devil Fruit:</h1>
  <br>
  <%# ************** Display Specific Devil Fruit ************** %>
  <div class="container">
    <div class="">
      <h3><%= @cart_item.devil_fruit.name %> 🍓</h3>
        <% if @cart_item.devil_fruit.photo.key.nil? %>
          <img src="https://cdn.shopify.com/s/files/1/0556/3822/9043/files/Fruit001.png?v=1650868361" alt="default photo">
        <% else %>
          <%= cl_image_tag @cart_item.devil_fruit.photo.key, crop: :fill %>
        <% end %>
      <li><%= @cart_item.devil_fruit.description %></li>
      <li><%= @cart_item.devil_fruit.price %> Berries</li>
      <li><%= link_to 'Go back to my Shopping Cart 🛒', shopping_cart_path(current_user.shopping_cart) %></li>
      <li><%= link_to 'Remove from Cart', cart_item_path(@cart_item), method: :delete, 'data-turbo-method': :delete %></li>
    </div>
  </div>
      <li><%= link_to 'All Devil Fruits', devil_fruits_path(@devil_fruit) %></li>
</div>

app/views/devil_fruits/edit.html.erb
<body class="form_background_img">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card my-5">
          <div class="card-header">
            <h3 class="text-center my-3">Edit Your Devil Fruit 🫐</h3>
          </div>
          <div class="card-body">
            <%= simple_form_for(@devil_fruit, method: :put) do |f| %>
              <div class="form-group">
                <%= f.label :name, class: "font-weight-bold" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :price, class: "font-weight-bold mt-3" %>
                <%= f.text_field :price, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :description, class: "font-weight-bold mt-3" %>
                <%= f.text_area :description, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= f.label :image, class: "form-label mt-3" %>
                <%= f.file_field :photo, class: "form-control" %>
              </div>
              <%= f.submit "Update Devil Fruit", class: "btn btn-info mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/devil_fruits/index.html.erb
<%# app/views/devil_fruits/index.html.erb %>

<div class="container my-12 mx-auto px-4 md:px-12">
  <h2 class="text-center font-monospace elegantshadow">Choose your Devil Fruit...Become invincible! </h2>

  <%# ************** Display Devil Fruit Cards ****** %>
    <div class="container">
    <div class="flex flex-wrap -mx-1 lg:-mx-4">
        <div class="row justify-content-center">
          <% @devil_fruits.each do |devil_fruit| %>
            <div class ="col-8 col-sm-6 col-md-4">
              <div class="card bg-light text-center mb-3 mt-3">
              <% if devil_fruit.photo.key.nil? %>
                <img src="https://cdn.shopify.com/s/files/1/0556/3822/9043/files/Fruit001.png?v=1650868361" alt="default photo">
              <% else %>
                <%= cl_image_tag devil_fruit.photo.key, height: 298, width: 298, crop: :fill %>
              <% end %>
                <div class="card-body">
                  <h5 class="card-text mb-1 text-xs font-monospace"> <%= devil_fruit.name %></h5>
                  <h5 class="card-text mb-1 text-xs font-monospace"><%= devil_fruit.price %> 💲Berrys</h5>
                  <p class="card-text  custom-btn btn-9 mt-5"> <%= link_to 'Show Devil Fruit 🍓', devil_fruit_path(devil_fruit), class:"text-decoration-none text-dark font-monospace"%></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>


  <%# ************** Create Devil Fruit ****** %>
  <p class="custom-btn btn-9"> <%= link_to 'Upload a new Devil Fruit 🍌', new_devil_fruit_path(@devil_fruit), class:"text-decoration-none text-dark font-monospace"%></p>
</div>

app/views/devil_fruits/new.html.erb
<body class="form_background_img">
  <div class="containerg">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-6">
        <div class="card-body">
          <div class="card-header">
            <h3 class="text-center my-3 font-monospace">Add Your Devil Fruit 🫐</h3>
              <%= simple_form_for(@devil_fruit) do |f| %>
                  <div class="form-group">
                    <%= f.label :name, class: "font-weight-bold font-monospace fs-5" %>
                    <%= f.text_field :name, class: "form-control form-width rounded-pill shadow bg-body-tertiary", placeholder: "XX XX no me"%>
                  </div>
                  <div class="form-group">
                    <%= f.label :price, class: "font-weight-bold font-monospace mt-3 fs-5" %>
                    <%= f.text_field :price, class: "form-control form-width rounded-pill shadow bg-body-tertiary", placeholder: "Berrys💲" %>
                  </div>
                  <div class="mb-3">
                    <%= f.label :image, class: "form-label font-monospace mt-3 fs-5" %>
                    <%= f.file_field :photo, class: "form-control form-width rounded-pill shadow bg-body-tertiary" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :description, class: "font-weight-bold font-monospace mt-1 fs-5" %>
                    <%= f.text_area :description, class: "form-control form-width rounded-pill shadow bg-body-tertiary", placeholder: "Talk about its super power" %>
                  </div>
                <%= f.submit "Add Devil Fruit", class: "btn btn-info mt-5 fs-6 rounded-pill shadow bg-body-tertiary" %>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</body>

app/views/devil_fruits/show.html.erb
<div class="df-card-container">
  <h1 class="font-alpha">Your chosen Devil Fruit:</h1>
  <br>
  <!-- Display Specific Devil Fruit -->
  <div class="devil-fruit-container">
    <div class="devil-fruit-card">
      <div class="devil-fruit-image">
        <% if @devil_fruit.photo.key.nil? %>
          <img src="https://cdn.shopify.com/s/files/1/0556/3822/9043/files/Fruit001.png?v=1650868361" alt="default photo">
        <% else %>
          <%= cl_image_tag @devil_fruit.photo.key, height: 298, width: 298, crop: :fit %>
        <% end %>
      </div>
      <div class="devil-fruit-details">
        <h3><%= @devil_fruit.name %> 🍓</h3>
        <ul>
          <li><%= @devil_fruit.description %></li>
          <li><%= @devil_fruit.price %> Berries</li>
        </ul>
      </div>
      <% if current_user %>
        <div class="devil-fruit-actions">
          <ul>
            <% if policy(@devil_fruit).edit? %>
              <li>
                <a class="button" style="--color: #96be25;" href="<%= edit_devil_fruit_path(@devil_fruit) %>" class="button">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Edit Devil Fruit
                </a>
              </li>
            <% end %>
            <% if policy(@devil_fruit).destroy? %>
              <li>
                <a class="button" style="--color: #ff1867;" href="<%= devil_fruit_path(@devil_fruit) %>" class="button" data-turbo-method="delete" data-turbo-confirm="Are you sure?">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Delete my Devil Fruit 🛒
                </a>
              </li>
            <% end %>
            <li>
              <a class="button" style="--color: #2596be;" href="<%= devil_fruit_cart_items_path(@devil_fruit) %>" class="button" data-turbo-method="post">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Add to my Shopping Cart 🛒
              </a>
            </li>
            <li>
              <a class="button" style="--color: #25a5be;" href="<%= shopping_cart_path(current_user.shopping_cart) %>">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Go to my Shopping Cart 🛒
              </a>
            </li>
                    </div>
                  <% end %>
          </ul>
    </div>
      <a class="button" style="--color: #2587be;" href="<%= devil_fruits_path(@devil_fruit) %>" class="button">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      All Devil Fruits
      </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devil Fruits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"  %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  <footer class="main-footer">
    <%= render "shared/footer"  %>
  </footer>
</html>

app/views/pages/home.html.erb
<%# app/views/pages/home.html.erb %>

<section class="mt-5">
  <div class="container text-center">
    <h1 class="font-monospace elegantshadow">Welcome to our Devil Fruit Shop! 🍇</h1>
    <h4 class="mt-4 fs-4 text-gradient"><%= link_to 'Go to shop 🛒', devil_fruits_path(@devil_fruit), class:"text-decoration-none text-dark font-monospace" %></h4>
  </div>
</section>

<div class="card-category front-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://staticg.sportskeeda.com/editor/2021/12/5ec3c-16395114659019-1920.jpg)">
</div>

app/views/shared/_footer.html.erb
<div class="ft">
<div class="footer">
  <div class="row">
    <div class="col">
      <img src="" class="logs">
      <p>Devil Fruits are mysterious, distinctive fruits scattered throughout the world, known for permanently granting their eaters superhuman powers and an equally permanent inability to swim. With only one notable exception, an individual can only acquire the powers of a single Devil Fruit and survive.</p>
    </div>
      <div class="col">
        <h3>office <div class="underline"><span></span></div></h3>
        <p>Rhoudani road</p>
        <p>rhoudani, 45  pin 30987</p>
        <p class="email-id">batch#1125@gamil.com</p>
        <p>+212 6 00 00 00 00 </p>
      </div>
      <div class="col">
        <h3>Links <div class="underline"><span></span></div></h3>
        <ul>
          <li><a href="">Home</a></li>
            <li><a href="">Services</a></li>
            <li><a href="">About Us</a></li>
            <li><a href="">Contacts</a></li>
        </ul>
      </div>
      <div class="col">
        <h3>Newsletter<div class="underline"><span></span></div></h3>
        <form >
        <i class="fas fa-envelope"></i>
        <input type="email" placeholder="Enter your email" requiered>
        <button type="submit"><i class="fas fa-arrow-right"></i></button>
        </form>
        <div class="social-icons d-flex">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-github"></i>
        <i class="fab fa-twitter"></i>
        </div>
      </div>
    </div>
      <hr>
  <p class="copyright">Batch#1125 -2023 - All rights Reserved</p>
  </div>

</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dlgrirjkk/image/upload/v1677859995/logo.png_cupbhs.png", class:"rounded-circle" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
         <li class="nav-item active">
            <%= form_with url: devil_fruits_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find a devil fruits"
            %>
            <%= submit_tag "Search", class: "btn " %>
        <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/AbderrahmanKro", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a new Devil Fruit", new_devil_fruit_path(@devil_fruit), class: "dropdown-item" %>
              <%= link_to "Show my Shopping Cart", shopping_cart_path(current_user.shopping_cart), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shopping_carts/show.html.erb
<%# app/view/shopping_carts/show.html.erb %>

<h3> Welcome to your Shopping Cart! 🛒 </h3>
  <div class="devil-fruit-container">
        <div class="devil-fruit-card">
        <div class="devil-fruit-image">
  <div>
    <h4 class="px-4 py-4">Items in your Cart:</h4>
        <% if @cart_items.count > 0 %>
          <% @cart_items.each do |cart_item| %>
          <% if cart_item.devil_fruit.photo.key.nil? %>
          <img src="https://cdn.shopify.com/s/files/1/0556/3822/9043/files/Fruit001.png?v=1650868361" alt="default photo">
        <% else %>
          <%= cl_image_tag cart_item.devil_fruit.photo.key, height: 100, width: 100, crop: :fit %>
        <% end %>
        </div>
          <ul>
            <li><%= link_to 'Remove from Cart', cart_item_path(cart_item), method: :delete, 'data-turbo-method': :delete %></li>
                  <div class="devil-fruit-details">

            <li><%= link_to cart_item.devil_fruit.name, cart_item_path(cart_item), class: "" %> - <%= cart_item.devil_fruit.price %> Berries</li>
            </div>
          </ul>
            <% end %>
            </div>
        <% else %>
          <p>No items in your cart yet!</p>
      <% end %>
  </div>
</div>